Update setversion.yml

diff --git a/.github/workflows/setversion.yml b/.github/workflows/setversion.yml
--- a/.github/workflows/setversion.yml
+++ b/.github/workflows/setversion.yml
@@ -16,11 +16,23 @@ jobs:
         env:
           GITHUB_CONTEXT: ${{ toJson(github) }}
         run: echo "$GITHUB_CONTEXT"
-      - name: listen for PR Comments
-        id: set_version_handler
-        uses: machine-learning-apps/actions-chatops@master
-        with:
-          TRIGGER_PHRASE: "/set-version"
+      - name: ensure formatting of version number
+        id: ensure_version_number
+        shell: bash
+        # we ensure that our versioning scheme matches v0.0.1A
+        run: |
+          [[ ${{ github.event.comment.body }} =~ ^/set-version version=v[0-9]+\.[0-9]+\.[0-9]+[a-zA-Z]{0,1}$ ]] && echo "::set-output name=VERSION_FORMATTED::true"
+      - name: ensure formatting of comment
+        if: ${{ steps.ensure_version_number.outputs.VERSION_FORMATTED != 'true' }}
+        # fail job if comment body does not contain the version in correct format
+        run: |
+          exit 1
+      - name: get version number
+        id: get_version_number
+        shell: bash
+        run: |
+          vno=$(echo ${{ github.event.comment.body }} | cut -d "=" -f 2)
+          echo "::set-output name=VERSION_NUMBER::$vno"
       - name: React to comment
         uses: dkershner6/reaction-action@v1
         with:
@@ -32,8 +44,8 @@ jobs:
         run: |
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-          gh pr checkout ${{ steps.set_version_handler.outputs.PULL_REQUEST_NUMBER }}
-          echo -n "${{ steps.set_version_handler.outputs.TRAILING_TOKEN }}" > version
+          gh pr checkout ${{ github.event.issue.number }}
+          echo -n "${{ steps.get_version_number.outputs.VERSION_NUMBER }}" > version
           git add -A
           git commit -m "[set-version-command] include/update version file"
           git push
